<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Navya Hooda">
<meta name="author" content="Mohammed Yusuf Shaikh">
<meta name="author" content="Shivank Goel">
<meta name="author" content="Vanshika Vanshika">
<meta name="author" content="Jena Shah">
<meta name="dcterms.date" content="2025-03-21">

<title>Effects of Different Pain Relievers and Dosages on Cognitive Retention</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="paper_files/libs/clipboard/clipboard.min.js"></script>
<script src="paper_files/libs/quarto-html/quarto.js"></script>
<script src="paper_files/libs/quarto-html/popper.min.js"></script>
<script src="paper_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="paper_files/libs/quarto-html/anchor.min.js"></script>
<link href="paper_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="paper_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="paper_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="paper_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="paper_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="paper_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="paper_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Effects of Different Pain Relievers and Dosages on Cognitive Retention</h1>
<p class="subtitle lead">Exploratory Data Analysis (EDA)</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-contents">
             <p>Navya Hooda </p>
             <p>Mohammed Yusuf Shaikh </p>
             <p>Shivank Goel </p>
             <p>Vanshika Vanshika </p>
             <p>Jena Shah </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 21, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<section id="relevant-background" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="relevant-background"><span class="header-section-number">1.1</span> Relevant Background</h2>
<p>Pain can make everyday tasks harder, particularly when mental focus and clarity are required. Common pain relievers like Aspirin, Paracetamol, and Tramadol are often used to reduce physical discomfort, but their impact on cognitive functions is not well understood. Recalling information, a task that demands mental effort, becomes more difficult when we’re in pain. This study investigates how different pain relievers (Aspirin, Paracetamol, and Tramadol) at standard dosages affect memory performance. It also looks at how varying dosages of each drug influence memory function. Since the ability to recall information is essential in many situations, understanding how pain relief might impact cognitive performance is important for managing pain without affecting productivity.</p>
</section>
<section id="research-questions" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="research-questions"><span class="header-section-number">1.2</span> Research Questions</h2>
<ol type="1">
<li><em>How does the type of pain reliever (Aspirin 500 mg, Paracetamol 500 mg, Tramadol 50 mg, and Placebo) affect cognitive task performance?</em></li>
<li><em>How does the dosage (low vs.&nbsp;high) of each drug affect cognitive retention, while accounting for confounding factors like age?</em></li>
</ol>
</section>
<section id="study-design" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="study-design"><span class="header-section-number">1.3</span> Study Design</h2>
<p>This study involves 2 factors, pain reliever type (4 levels) and dosage(2 levels). Crossing them provides us with <em>8 treatment groups</em>, with <strong>30 participants</strong> assigned to each. The groups are as follows:</p>
<ol type="1">
<li>Aspirin 500 mg (Low)</li>
<li>Aspirin 1000 mg (High)</li>
<li>Paracetamol 500 mg (Low)</li>
<li>Paracetamol 1000 mg (High)</li>
<li>Tramadol 50 mg (Low)</li>
<li>Tramadol 100 mg (High)</li>
<li>Placebo (Low)</li>
<li>Placebo (High)</li>
</ol>
<p>This results in <strong>240 total observations</strong> (8 × 30 = 240).</p>
</section>
<section id="confounding-variable-age" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="confounding-variable-age"><span class="header-section-number">1.4</span> Confounding Variable: Age</h2>
<p>To reduce bias, we consider to control the experiment by controlling participant ages to be 18+. Hence in this study <strong>age</strong> acts as a <strong>confounding variable</strong>. Participants will be categorized into three groups evenly to prevent bias created through age. The groups are as follows:</p>
<ol type="1">
<li>18–34 years</li>
<li>35–50 years</li>
<li>50+ years</li>
</ol>
</section>
<section id="quantitative-and-qualitative-variables" class="level2" data-number="1.5">
<h2 data-number="1.5" class="anchored" data-anchor-id="quantitative-and-qualitative-variables"><span class="header-section-number">1.5</span> Quantitative and Qualitative Variables</h2>
<p>In our study the quantitative and qualitative variables are as follows:</p>
<ol type="1">
<li>Quantitative variables: Memory Game Scores, Memory Test Cards Scores</li>
<li>Qualitative variables: Type of pain reliever, dosage level (low/high)</li>
</ol>
</section>
<section id="data-analysis-method" class="level2" data-number="1.6">
<h2 data-number="1.6" class="anchored" data-anchor-id="data-analysis-method"><span class="header-section-number">1.6</span> Data Analysis Method</h2>
<p>We will use <strong>one-way ANOVA</strong> to analyze the effects of different pain relievers on memory performance. Similarly, we will use <strong>two-way ANOVA</strong> to analyze the effects of different dosage levels per drug type on memory performance and cognitive retention.</p>
</section>
</section>
<section id="summary-statistics" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Summary Statistics</h1>
<section id="summary-of-quantitative-variables" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="summary-of-quantitative-variables"><span class="header-section-number">2.1</span> Summary of quantitative variables</h2>
<p><a href="#tbl-summary-1" class="quarto-xref">Table&nbsp;1</a> shows the summary statistics of memory game scores before and after the treatment. The mean is similar across all groups, however, the standard deviation (SD) is relatively high. The median game scores remain close to the mean, and the IQR (Interquartile Range) is smaller than the SD. The cards memory task shows little change before and after treatment, suggesting that pain relievers may not have a major effect on this specific task.</p>
<p>Evident through the results on <strong>?@tbl-summary-6</strong>, Paracetamol is the drug that has the greatest mean &amp; median improvement in the game scores after administering the drug (without dosage taken into account). Aspirin appears to negatively impact the results of the game after being given to people, this was seen through the mean and median improvements.</p>
<div class="cell">
<div id="tbl-summary-1" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-summary-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Summary Statistics for Quantitative Variables
</figcaption>
<div aria-describedby="tbl-summary-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">

</div>
</div>
</figure>
</div>
</div>
<div class="cell">
<div id="tbl-summary-2" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-summary-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Summary of Drug Types
</figcaption>
<div aria-describedby="tbl-summary-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">

</div>
</div>
</figure>
</div>
</div>
<div class="cell">
<div id="tbl-summary-3" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-summary-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Summary of Dosage Levels
</figcaption>
<div aria-describedby="tbl-summary-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Dosage</th>
<th style="text-align: right;">Count</th>
<th style="text-align: right;">Percentage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">High</td>
<td style="text-align: right;">120</td>
<td style="text-align: right;">50</td>
</tr>
<tr class="even">
<td style="text-align: left;">Low</td>
<td style="text-align: right;">120</td>
<td style="text-align: right;">50</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell">
<div id="tbl-summary-5" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-summary-5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Summary of Age Groups
</figcaption>
<div aria-describedby="tbl-summary-5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Age_Group</th>
<th style="text-align: right;">Count</th>
<th style="text-align: right;">Percentage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">18-34</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">33.33</td>
</tr>
<tr class="even">
<td style="text-align: left;">35-50</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">33.33</td>
</tr>
<tr class="odd">
<td style="text-align: left;">50+</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">33.33</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="summary-of-counts-and-percentage-for-qualitative-variables" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="summary-of-counts-and-percentage-for-qualitative-variables"><span class="header-section-number">2.2</span> Summary of counts and percentage for qualitative variables</h2>
<p><a href="#tbl-summary-2" class="quarto-xref">Table&nbsp;2</a> shows the distribution of participants across drug types. Aspirin, Paracetamol, and Tramadol, and Placebo each have 60 participants (25%), ensuring balance.</p>
<p><a href="#tbl-summary-3" class="quarto-xref">Table&nbsp;3</a> shows the dosage levels assigned to participants. There is an equal split between high-dose (120 participants, 50%) and low-dose (120 participants, 50%) conditions.</p>
</section>
<section id="confounding-variable" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="confounding-variable"><span class="header-section-number">2.3</span> Confounding Variable</h2>
<p><a href="#tbl-summary-5" class="quarto-xref">Table&nbsp;4</a> shows the breakdown of age groups, which is a confounding variable in this study. The three age groups: 18–34, 35–50, and 50+ each have 80 participants (33.33%).</p>
</section>
</section>
<section id="plots" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Plots</h1>
<div class="cell">
<div class="cell-output-display">
<div id="fig-boxplot-game-scores" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-boxplot-game-scores-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="paper_files/figure-html/fig-boxplot-game-scores-1.png" class="img-fluid figure-img" width="2700">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-boxplot-game-scores-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Memory Game Scores by Drug Type and Dosage Level
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-boxplot-card-scores" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-boxplot-card-scores-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="paper_files/figure-html/fig-boxplot-card-scores-1.png" class="img-fluid figure-img" width="2700">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-boxplot-card-scores-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Memory Game Scores by Drug Type and Dosage Level
</figcaption>
</figure>
</div>
</div>
</div>
<section id="game-score-distribution-before-and-after-treatment" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="game-score-distribution-before-and-after-treatment"><span class="header-section-number">3.1</span> Game Score Distribution Before and After Treatment</h2>
<p><strong>?@fig-boxplot-scores</strong> shows the distribution of memory game scores before and after treatment across different drug types using box plots.</p>
<ol type="1">
<li>The median scores for all drugs appear similar before treatment.</li>
<li>Tramadol has a higher median than other drugs both before and after treatment.</li>
<li>The Placebo group has a slightly lower median score compared to other drugs.</li>
<li>There is one outlier in the Tramadol group before treatment.</li>
<li>The (IQR) is <strong>similar across all drug types</strong>, though Tramadol sees a decrease in its IQR in the memory game scores after treatment.</li>
</ol>
<p>These boxplots provide an initial comparison of cognitive performance changes before and after drug administration.</p>
</section>
<section id="memory-card-score-distribution-before-and-after-treatment" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="memory-card-score-distribution-before-and-after-treatment"><span class="header-section-number">3.2</span> Memory Card Score Distribution Before and After Treatment</h2>
<p><strong>?@fig-boxplot-cards</strong> shows the distribution of <strong>memory card scores before and after treatment</strong> across drug types.</p>
<ol type="1">
<li>Before treatment, the scores are relatively high across all groups, with Paracetamol and Placebo showing slightly higher medians than the others.</li>
<li>After treatment, the distributions remain similar, though there is a slight increase in spread for Aspirin, Paracetamol, and Placebo.</li>
<li>There is a slight decrease in the IQR of Tramadol.</li>
<li>Outliers are present in all groups, indicating some variability in memory card performance across individuals.</li>
</ol>
</section>
</section>
<section id="assumptions" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Assumptions</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the model (Two-Way ANOVA using lm)</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>anova_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(memory_game_score <span class="sc">~</span> drug <span class="sc">*</span> dosage_level, <span class="at">data =</span> clean_data)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract Coefficients into a Data Frame</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>anova_table <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">summary</span>(anova_model)<span class="sc">$</span>coefficients)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(anova_table) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Estimate"</span>, <span class="st">"Std. Error"</span>, <span class="st">"t value"</span>, <span class="st">"Pr(&gt;|t|)"</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Format p-values for readability</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>anova_table <span class="ot">&lt;-</span> anova_table <span class="sc">%&gt;%</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">`</span><span class="at">Significance</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">case_when</span>(</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Pr(&gt;|t|)</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="fl">0.001</span> <span class="sc">~</span> <span class="st">"***"</span>,</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Pr(&gt;|t|)</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="fl">0.01</span> <span class="sc">~</span> <span class="st">"**"</span>,</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Pr(&gt;|t|)</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="fl">0.05</span> <span class="sc">~</span> <span class="st">"*"</span>,</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Pr(&gt;|t|)</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="fl">0.1</span> <span class="sc">~</span> <span class="st">"."</span>,</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>    <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">""</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>  ))</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Create Table Output</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(anova_table, <span class="at">format =</span> <span class="st">"html"</span>, <span class="at">digits =</span> <span class="dv">3</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">FALSE</span>, <span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"hover"</span>, <span class="st">"condensed"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Std. Error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">t value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Pr(&gt;|t|)</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Significance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">60.020</td>
<td style="text-align: right;">2.839</td>
<td style="text-align: right;">21.138</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: left;">***</td>
</tr>
<tr class="even">
<td style="text-align: left;">drugParacetamol</td>
<td style="text-align: right;">1.327</td>
<td style="text-align: right;">4.015</td>
<td style="text-align: right;">0.330</td>
<td style="text-align: right;">0.741</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">drugPlacebo</td>
<td style="text-align: right;">-3.053</td>
<td style="text-align: right;">4.015</td>
<td style="text-align: right;">-0.760</td>
<td style="text-align: right;">0.448</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">drugTramadol</td>
<td style="text-align: right;">7.417</td>
<td style="text-align: right;">4.015</td>
<td style="text-align: right;">1.847</td>
<td style="text-align: right;">0.066</td>
<td style="text-align: left;">.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">dosage_levelHigh</td>
<td style="text-align: right;">2.180</td>
<td style="text-align: right;">4.015</td>
<td style="text-align: right;">0.543</td>
<td style="text-align: right;">0.588</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">drugParacetamol:dosage_levelHigh</td>
<td style="text-align: right;">-1.290</td>
<td style="text-align: right;">5.679</td>
<td style="text-align: right;">-0.227</td>
<td style="text-align: right;">0.820</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">drugPlacebo:dosage_levelHigh</td>
<td style="text-align: right;">6.517</td>
<td style="text-align: right;">5.679</td>
<td style="text-align: right;">1.148</td>
<td style="text-align: right;">0.252</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">drugTramadol:dosage_levelHigh</td>
<td style="text-align: right;">-4.880</td>
<td style="text-align: right;">5.679</td>
<td style="text-align: right;">-0.859</td>
<td style="text-align: right;">0.391</td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>


</div>
</div>
<section id="checking-model-assumptions" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="checking-model-assumptions"><span class="header-section-number">4.1</span> Checking Model Assumptions</h2>
<strong>Repeated Measures ANOVA</strong> (To be changed) When performing a repeated measures ANOVA, it is essential to verify that the underlying assumptions of the test are met. These assumptions include:
<p>This document outlines the methods and tests used to verify these assumptions.</p>
<p>The assumption of normality was tested using the Shapiro-Wilk test. The Shapiro-Wilk test evaluates the null hypothesis that the data is normally distributed. The test statistic ( W ) and the corresponding ( p )-value were calculated for each combination of the factors (Drug, DosageLevel, and Time).</p>
<p>If the ( p )-value is greater than 0.05, we fail to reject the null hypothesis and assume normality. Otherwise, the normality assumption is violated.</p>
<p>Q-Q plots were generated to visually inspect the normality assumption. If the points in the Q-Q plot lie approximately on the reference line, the data can be assumed to be normally distributed.</p>
<p>The assumption of sphericity was tested using Mauchly’s test. Sphericity refers to the condition where the variances of the differences between all combinations of related groups are equal.</p>
<p>If the ( p )-value from Mauchly’s test is greater than 0.05, we fail to reject the null hypothesis and assume sphericity. If the assumption is violated, corrections such as Greenhouse-Geisser or Huynh-Feldt should be applied.</p>
<p>The assumption of homogeneity of variance was tested using Levene’s test. This test evaluates whether the variances of the dependent variable are equal across all groups formed by the combinations of the factors (Drug, DosageLevel, and Time).</p>
<p>If the ( p )-value from Levene’s test is greater than 0.05, we fail to reject the null hypothesis and assume homogeneity of variance. If the assumption is violated, transformations or alternative statistical methods may be required.</p>
<p>Boxplots were generated to visually inspect the homogeneity of variance. If the boxplots show similar spreads across groups, the assumption is likely met.</p>
<p>The results of the assumption tests (Shapiro-Wilk, Mauchly’s, and Levene’s) were used to determine whether the assumptions of normality, sphericity, and homogeneity of variance were met. If any assumptions were violated, appropriate corrections or alternative methods were considered before proceeding with the repeated measures ANOVA.</p>
</section>
</section>
<section id="check-for-homogeneity-of-variance-using-levenes-test" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Check for Homogeneity of Variance using Levene’s Test</h1>
<p>levene_test &lt;- leveneTest(GameScore ~ Drug * DosageLevel * Time, data = clean_data) print(levene_test)</p>
</section>
<section id="visual-check-for-homogeneity-of-variance-using-boxplots" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Visual check for homogeneity of variance using boxplots</h1>
<p>ggplot(clean_data, aes(x = interaction(Drug, DosageLevel, Time), y = GameScore)) + geom_boxplot() + theme_minimal() + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + ggtitle(“Boxplots for Homogeneity of Variance Check”)</p>
<p>```</p>
<p>We assessed the homogeneity of variance and normality of residuals using diagnostic plots to validate the assumptions of our ANOVA tests. (<strong>?@fig-assump-one</strong> &amp; <strong>?@fig-assump-two</strong>).</p>
<p><strong>One-way ANOVA</strong></p>
<p><em>Independence:</em> For our one-way ANOVA model, we have independence because our observations are independent within and across the groups i.e all participants were randomly assigned a pain reliever, and there was no relationships between observations (i.e repeated participants, treatments etc.)</p>
<p><em>Homogeneity of Variance:</em> The reference line in <strong>?@fig-assump-one</strong> relatively flat and horizontal which indicates that variance is approximately equal across groups. Thus, the assumption of homogeneity of variance is not significantly violated.</p>
<p><em>Normality of Residuals:</em> The residuals are approximately normally distributed in <strong>?@fig-assump-one</strong> since the density plot on the right appears close to a normal distribution.</p>
<p><strong>Two-way ANOVA</strong></p>
<p><em>Independence:</em> For our two-way ANOVA model, the different combinations of pain reliever type and dosage levels were randomly assigned to all participants, in random order.</p>
<p><em>Homogeneity of Variance:</em> In <strong>?@fig-assump-two</strong> the left plot shows some deviation from a perfectly flat line and has minor fluctuations, especially at certain levels of drug type and dosage. Despite some variation, the overall trend does not show extreme violations of homogeneity.</p>
<p><em>Normality of Residuals:</em> In <strong>?@fig-assump-two</strong> the density plot on the right shows that the residuals follow a roughly normal distribution even though minor deviations are present.</p>
<p><strong>Conclusion</strong></p>
<p>Both models satisfy the assumptions of homogeneity of variance and normality of residuals well enough. There are slight deviations in the two-way ANOVA model, but they are not severe enough to invalidate the analysis. Therefore, we proceed with the ANOVA tests.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>