
---
title: "Analyzing How Organization Size, Sector, and Cybersecurity Strategies Influence Impacts on Cyberattacks"
subtitle: "Based on Data Collected From the University of Queensland"
author: 
  - Shivank Goel
thanks: "Code and data are available at: https://github.com/shivankgoel003/DataBreach_Ransomware_Stats"
date: today
date-format: long
abstract: "Undoubtedly as technology is progressing and we are stepping more closer to the digital world, the digital threats are also increasingly rapidly. This study discusses the influence of organizational size, sector, and cybersecurity strategies on cyberattack impacts. Utilizing a dataset from the University of Queensland about data breaches and ransomware attacks from 2004 to 2019, we analyze the trends and correlations and study how different factors contribute to the severity and frequency of these incidents. Our analysis reveals key insights: larger organizations report more cyber incidents, sectors like healthcare and education are frequent targets, and cybersecurity frameworks significantly help in reducing the user impact. These findings highlight critical areas for how organizations can improve their security and protect their data."
header-includes:
   - \usepackage{tikz}
   - \usetikzlibrary{shapes.geometric, arrows.meta, positioning, fit, calc}
   - \usepackage{pgfplots} 
   - \usepackage{float}
   - \usepackage{booktabs}
   - \usepackage{longtable}

format: pdf
number-sections: true
bibliography: references.bib
toc: true
---

```{r}
#| include: false
#| warning: false
#| message: false

library(tidyverse)
library(readxl)
library(here)

breach_data <- read.csv(here("data/analysis_data/breach_data.csv"))
```


# Introduction

Therefore, in response to such attacks, there is a need for a plan, that not just keep the intruder or hackers out but also quickly alert if an attack does happen. Our study looks at cyber resilience, which is “ the ability to anticipate, withstand, recover from, and adapt to adverse conditions, stresses, attacks, or compromises on systems that use or are enabled by cyber resources.” as defined by National Institute of Standards and Technology [@NISTGlossary2023]. We break our study into three major research questions, which forms the thesis of our study:

**RQ1**: How do organizational factors such as size and sector, influence the severity of cyber breaches experienced by companies?

**RQ2**: Which cybersecurity strategies, including frameworks, policies, and preventive measures, are the most effective one, in reducing the damage caused by cyber attacks?

**RQ3**: In what ways do the industry type and digital dependence of a business affect the overall impact of a cyber attack, in terms of preserving confidentiality, integrity and availability of data?

We also plotted a bar graph @fig-sector to count the number of incidents across various sectors. The bar chart clearly indicates that the 'Human Health Activities' sector has the highest count of incidents, standing out significantly from the other sectors. This might suggest that health sector is a more frequent target for cyber incidents or probably it is more diligent in reporting such events. The other sectors show a range of incident counts, with most appearing to have far fewer incidents in comparison. This could point to different levels of risk exposure, varying security measures, or reporting practices across these sectors. 




\newpage






# References
